language: php

php:
  - 7.4

before_script:
  - cp .env.travis .env
  #  - mysql -e 'CREATE DATABASE mtnview_test;'
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
